template: testify
packages:
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: directive/mocks
      pkgname: mocks
      filename: mock_OpenFGAServiceClient.go
    interfaces:
      OpenFGAServiceClient:
        config:
          structname: OpenFGAServiceClient
  github.com/platform-mesh/golang-commons/fga/store:
    config:
      dir: fga/store/mocks
      pkgname: mocks
      filename: mock_FGAStoreHelper.go
    interfaces:
      FGAStoreHelper:
        config:
          structname: FGAStoreHelper
  github.com/platform-mesh/golang-commons/policy_services:
    config:
      dir: fga/policy_services/mocks
      pkgname: mocks
      filename: mock_TenantIdReader.go
    interfaces:
      TenantIdReader:
        config:
          structname: TenantIdReader
