version = 1
SPDX-PackageName = "golang-commons"
SPDX-PackageDownloadLocation = "https://github.com/platform-mesh/golang-commons"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Platform Mesh contributors and golang-commons contributors."
SPDX-License-Identifier = "Apache-2.0"
